/**
 * Dados seed/mock para Produção
 */

import type { 
  OrdemProducaoCompleta, 
  DashboardSetorData,
  ConsultaMaterial
} from './producao.types';

// Mock de Ordens de Produção
export const ordensMock: OrdemProducaoCompleta[] = [
  {
    id: '1',
    numero: 'OP-2024-001',
    clienteId: '1',
    clienteNome: 'Restaurante Bom Sabor',
    dataAbertura: '2024-02-01T08:00:00Z',
    dataPrevista: '2024-02-10T18:00:00Z',
    prioridade: 'Alta',
    status: 'Em Producao',
    itens: [
      {
        id: '1-1',
        ordemId: '1',
        produtoId: 'BANC-001',
        produtoCodigo: 'BANC-304-2000X700',
        produtoNome: 'Bancada Inox 304 com Encosto 2000x700mm',
        quantidade: 2,
        unidade: 'UN',
        setorAtual: 'Corte',
        status: 'Em Producao',
        progresso: 45,
        iniciadoEm: '2024-02-01T09:00:00Z',
        tempoProducao: 120,
        materiaisNecessarios: [
          {
            produtoId: 'CHAPA-304-1.2',
            produtoCodigo: 'CH-304-1.2',
            produtoNome: 'Chapa Inox 304 espessura 1,2mm',
            quantidadeNecessaria: 5.6,
            quantidadeDisponivel: 8.0,
            unidade: 'M2',
            faltante: 0,
          },
          {
            produtoId: 'TUBO-304-38',
            produtoCodigo: 'TB-304-38',
            produtoNome: 'Tubo Redondo Inox 304 Ø38mm',
            quantidadeNecessaria: 12,
            quantidadeDisponivel: 15,
            unidade: 'MT',
            faltante: 0,
          },
        ],
        materiaisDisponiveis: true,
        nestingId: 'NEST-001',
        consumoChapa: {
          tipo: 'Chapa',
          material: '304',
          espessura: 1.2,
          largura: 1220,
          comprimento: 2440,
          peso: 45.8,
          area: 2.98,
          aproveitamento: 85,
          perdas: 15,
        },
      },
      {
        id: '1-2',
        ordemId: '1',
        produtoId: 'PRAT-001',
        produtoCodigo: 'PRAT-304-2000X600',
        produtoNome: 'Prateleira Inox 304 2000x600mm',
        quantidade: 4,
        unidade: 'UN',
        setorAtual: 'Dobra',
        status: 'Em Producao',
        progresso: 75,
        iniciadoEm: '2024-02-01T10:30:00Z',
        tempoProducao: 90,
        materiaisNecessarios: [
          {
            produtoId: 'CHAPA-304-1.0',
            produtoCodigo: 'CH-304-1.0',
            produtoNome: 'Chapa Inox 304 espessura 1,0mm',
            quantidadeNecessaria: 4.8,
            quantidadeDisponivel: 6.0,
            unidade: 'M2',
            faltante: 0,
          },
        ],
        materiaisDisponiveis: true,
      },
    ],
    observacoes: 'Cliente solicitou acabamento escovado',
    totalItens: 2,
    itensConcluidos: 0,
    progressoGeral: 60,
  },
  {
    id: '2',
    numero: 'OP-2024-002',
    clienteId: '2',
    clienteNome: 'Padaria Central',
    dataAbertura: '2024-02-02T08:00:00Z',
    dataPrevista: '2024-02-08T18:00:00Z',
    prioridade: 'Urgente',
    status: 'Em Producao',
    itens: [
      {
        id: '2-1',
        ordemId: '2',
        produtoId: 'MESA-001',
        produtoCodigo: 'MESA-430-1500X800',
        produtoNome: 'Mesa Central Inox 430 1500x800mm',
        quantidade: 1,
        unidade: 'UN',
        setorAtual: 'Solda',
        status: 'Em Producao',
        progresso: 30,
        iniciadoEm: '2024-02-02T09:15:00Z',
        tempoProducao: 60,
        materiaisNecessarios: [
          {
            produtoId: 'CHAPA-430-1.2',
            produtoCodigo: 'CH-430-1.2',
            produtoNome: 'Chapa Inox 430 espessura 1,2mm',
            quantidadeNecessaria: 2.4,
            quantidadeDisponivel: 1.0,
            unidade: 'M2',
            faltante: 1.4,
          },
        ],
        materiaisDisponiveis: false,
      },
    ],
    totalItens: 1,
    itensConcluidos: 0,
    progressoGeral: 30,
  },
];

// Mock de Dashboard por Setor
export const dashboardMock: DashboardSetorData[] = [
  {
    setor: 'Corte',
    itensAguardando: 3,
    itensEmProducao: 2,
    itensConcluidos: 8,
    itensRejeitados: 0,
    tempoMedioProducao: 45,
    eficiencia: 92,
    ultimaAtualizacao: new Date().toISOString(),
  },
  {
    setor: 'Dobra',
    itensAguardando: 2,
    itensEmProducao: 3,
    itensConcluidos: 6,
    itensRejeitados: 1,
    tempoMedioProducao: 35,
    eficiencia: 88,
    ultimaAtualizacao: new Date().toISOString(),
  },
  {
    setor: 'Solda',
    itensAguardando: 4,
    itensEmProducao: 2,
    itensConcluidos: 5,
    itensRejeitados: 0,
    tempoMedioProducao: 65,
    eficiencia: 85,
    ultimaAtualizacao: new Date().toISOString(),
  },
  {
    setor: 'Acabamento',
    itensAguardando: 5,
    itensEmProducao: 1,
    itensConcluidos: 7,
    itensRejeitados: 0,
    tempoMedioProducao: 40,
    eficiencia: 90,
    ultimaAtualizacao: new Date().toISOString(),
  },
  {
    setor: 'Montagem',
    itensAguardando: 3,
    itensEmProducao: 2,
    itensConcluidos: 4,
    itensRejeitados: 0,
    tempoMedioProducao: 55,
    eficiencia: 87,
    ultimaAtualizacao: new Date().toISOString(),
  },
  {
    setor: 'Qualidade',
    itensAguardando: 2,
    itensEmProducao: 1,
    itensConcluidos: 9,
    itensRejeitados: 1,
    tempoMedioProducao: 25,
    eficiencia: 94,
    ultimaAtualizacao: new Date().toISOString(),
  },
  {
    setor: 'Expedicao',
    itensAguardando: 1,
    itensEmProducao: 0,
    itensConcluidos: 10,
    itensRejeitados: 0,
    tempoMedioProducao: 20,
    eficiencia: 96,
    ultimaAtualizacao: new Date().toISOString(),
  },
];

// Mock de Materiais
export const materiaisMock: ConsultaMaterial[] = [
  {
    produtoId: 'CHAPA-304-1.2',
    produtoCodigo: 'CH-304-1.2',
    produtoNome: 'Chapa Inox 304 espessura 1,2mm',
    estoque: 15.5,
    reservado: 8.0,
    disponivel: 7.5,
    unidade: 'M2',
    localizacao: 'Almoxarifado A - Prateleira 3',
    estoqueMinimo: 5.0,
    baixoEstoque: false,
  },
  {
    produtoId: 'CHAPA-304-1.0',
    produtoCodigo: 'CH-304-1.0',
    produtoNome: 'Chapa Inox 304 espessura 1,0mm',
    estoque: 8.2,
    reservado: 6.0,
    disponivel: 2.2,
    unidade: 'M2',
    localizacao: 'Almoxarifado A - Prateleira 2',
    estoqueMinimo: 5.0,
    baixoEstoque: true,
  },
  {
    produtoId: 'CHAPA-430-1.2',
    produtoCodigo: 'CH-430-1.2',
    produtoNome: 'Chapa Inox 430 espessura 1,2mm',
    estoque: 3.5,
    reservado: 2.5,
    disponivel: 1.0,
    unidade: 'M2',
    localizacao: 'Almoxarifado A - Prateleira 5',
    estoqueMinimo: 4.0,
    baixoEstoque: true,
  },
  {
    produtoId: 'TUBO-304-38',
    produtoCodigo: 'TB-304-38',
    produtoNome: 'Tubo Redondo Inox 304 Ø38mm',
    estoque: 45,
    reservado: 15,
    disponivel: 30,
    unidade: 'MT',
    localizacao: 'Almoxarifado B - Rack Tubos',
    estoqueMinimo: 20,
    baixoEstoque: false,
  },
];
