/**
 * Dados seed para Produtos
 */

import { Produto } from './produtos.types';
import { newId } from '@/shared/types/ids';
import { toISOString } from '@/shared/lib/format';

export const produtosSeed: Produto[] = [
  {
    id: newId(),
    codigo: 'PROD-001',
    nome: 'Chapa de Aço 1020',
    descricao: 'Chapa de aço carbono 1020, espessura 3mm',
    tipo: 'Matéria-Prima',
    unidade: 'KG',
    preco: 8.50,
    custo: 6.20,
    estoque: 1500,
    estoqueMinimo: 500,
    ativo: true,
    criadoEm: toISOString(new Date('2024-01-10')),
    atualizadoEm: toISOString(new Date('2024-01-10')),
  },
  {
    id: newId(),
    codigo: 'PROD-002',
    nome: 'Parafuso M8x20',
    descricao: 'Parafuso sextavado M8x20mm, aço inox',
    tipo: 'Componente',
    unidade: 'UN',
    preco: 0.85,
    custo: 0.45,
    estoque: 5000,
    estoqueMinimo: 1000,
    ativo: true,
    criadoEm: toISOString(new Date('2024-01-12')),
    atualizadoEm: toISOString(new Date('2024-01-12')),
  },
  {
    id: newId(),
    codigo: 'PROD-003',
    nome: 'Estrutura Metálica Tipo A',
    descricao: 'Estrutura metálica soldada, dimensões 2x3m',
    tipo: 'Semiacabado',
    unidade: 'UN',
    preco: 1250.00,
    custo: 850.00,
    estoque: 25,
    estoqueMinimo: 10,
    ativo: true,
    criadoEm: toISOString(new Date('2024-01-15')),
    atualizadoEm: toISOString(new Date('2024-01-15')),
  },
  {
    id: newId(),
    codigo: 'PROD-004',
    nome: 'Portão Industrial Completo',
    descricao: 'Portão industrial automatizado 4x4m',
    tipo: 'Acabado',
    unidade: 'UN',
    preco: 8500.00,
    custo: 5200.00,
    estoque: 3,
    estoqueMinimo: 2,
    ativo: true,
    criadoEm: toISOString(new Date('2024-01-20')),
    atualizadoEm: toISOString(new Date('2024-01-20')),
  },
  {
    id: newId(),
    codigo: 'PROD-005',
    nome: 'Tinta Epóxi Cinza',
    descricao: 'Tinta epóxi para acabamento industrial',
    tipo: 'Matéria-Prima',
    unidade: 'LT',
    preco: 45.00,
    custo: 28.00,
    estoque: 150,
    estoqueMinimo: 50,
    ativo: true,
    criadoEm: toISOString(new Date('2024-01-22')),
    atualizadoEm: toISOString(new Date('2024-01-22')),
  },
  {
    id: newId(),
    codigo: 'PROD-006',
    nome: 'Perfil U 50mm',
    descricao: 'Perfil em U de aço, largura 50mm',
    tipo: 'Matéria-Prima',
    unidade: 'MT',
    preco: 12.50,
    custo: 9.00,
    estoque: 800,
    estoqueMinimo: 200,
    ativo: true,
    criadoEm: toISOString(new Date('2024-01-25')),
    atualizadoEm: toISOString(new Date('2024-01-25')),
  },
  {
    id: newId(),
    codigo: 'PROD-007',
    nome: 'Grade de Proteção 1x2m',
    descricao: 'Grade de proteção em aço, malha 5cm',
    tipo: 'Semiacabado',
    unidade: 'UN',
    preco: 280.00,
    custo: 180.00,
    estoque: 45,
    estoqueMinimo: 15,
    ativo: true,
    criadoEm: toISOString(new Date('2024-01-28')),
    atualizadoEm: toISOString(new Date('2024-01-28')),
  },
  {
    id: newId(),
    codigo: 'PROD-008',
    nome: 'Eletrodo E6013 3.25mm',
    descricao: 'Eletrodo para solda elétrica',
    tipo: 'Matéria-Prima',
    unidade: 'KG',
    preco: 18.00,
    custo: 12.50,
    estoque: 120,
    estoqueMinimo: 50,
    ativo: true,
    criadoEm: toISOString(new Date('2024-02-01')),
    atualizadoEm: toISOString(new Date('2024-02-01')),
  },
];
