import { Insumo, MateriaPrima, PeNivelador, Parafuso, ProdutoPadrao } from './types';

/**
 * Catálogo de Insumos - Dados Seed
 */

// Matérias Primas - Chapas de Inox
export const materiasPrimas: MateriaPrima[] = [
  {
    id: 'mp-001',
    codigo: 'MP-001',
    nome: 'Chapa Inox 304 #22 (0,80mm)',
    descricao: 'Chapa de aço inoxidável AISI 304, espessura 0,80mm',
    tipo: 'materia-prima',
    material: 'inox-304',
    espessura: 0.8,
    largura: 1000,
    comprimento: 2000,
    peso: 12.56,
    unidade: 'mt2',
    custoUnitario: 85.50,
    estoque: 45,
    fornecedor: 'Inox SP',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mp-002',
    codigo: 'MP-002',
    nome: 'Chapa Inox 304 #20 (1,00mm)',
    descricao: 'Chapa de aço inoxidável AISI 304, espessura 1,00mm',
    tipo: 'materia-prima',
    material: 'inox-304',
    espessura: 1.0,
    largura: 1000,
    comprimento: 2000,
    peso: 15.7,
    unidade: 'mt2',
    custoUnitario: 95.00,
    estoque: 38,
    fornecedor: 'Inox SP',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mp-003',
    codigo: 'MP-003',
    nome: 'Chapa Inox 304 #18 (1,20mm)',
    descricao: 'Chapa de aço inoxidável AISI 304, espessura 1,20mm',
    tipo: 'materia-prima',
    material: 'inox-304',
    espessura: 1.2,
    largura: 1000,
    comprimento: 2000,
    peso: 18.84,
    unidade: 'mt2',
    custoUnitario: 108.00,
    estoque: 32,
    fornecedor: 'Inox SP',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mp-004',
    codigo: 'MP-004',
    nome: 'Chapa Inox 304 #16 (1,50mm)',
    descricao: 'Chapa de aço inoxidável AISI 304, espessura 1,50mm',
    tipo: 'materia-prima',
    material: 'inox-304',
    espessura: 1.5,
    largura: 1000,
    comprimento: 2000,
    peso: 23.55,
    unidade: 'mt2',
    custoUnitario: 125.00,
    estoque: 28,
    fornecedor: 'Inox SP',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mp-005',
    codigo: 'MP-005',
    nome: 'Chapa Inox 430 #22 (0,80mm)',
    descricao: 'Chapa de aço inoxidável AISI 430, espessura 0,80mm',
    tipo: 'materia-prima',
    material: 'inox-430',
    espessura: 0.8,
    largura: 1000,
    comprimento: 2000,
    peso: 12.56,
    unidade: 'mt2',
    custoUnitario: 62.00,
    estoque: 55,
    fornecedor: 'Inox SP',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Pés Niveladores
export const pesNiveladores: PeNivelador[] = [
  {
    id: 'pn-001',
    codigo: 'PN-001',
    nome: 'Pé Nivelador M10 x 50mm',
    descricao: 'Pé nivelador regulável, rosca M10, altura 50mm',
    tipo: 'pes-niveladores',
    altura: 50,
    cargaMaxima: 150,
    rosca: 'M10',
    material: 'Aço zincado',
    unidade: 'un',
    custoUnitario: 3.20,
    estoque: 500,
    fornecedor: 'Comercial Parafusos',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pn-002',
    codigo: 'PN-002',
    nome: 'Pé Nivelador M12 x 80mm',
    descricao: 'Pé nivelador regulável, rosca M12, altura 80mm',
    tipo: 'pes-niveladores',
    altura: 80,
    cargaMaxima: 200,
    rosca: 'M12',
    material: 'Aço zincado',
    unidade: 'un',
    custoUnitario: 4.50,
    estoque: 350,
    fornecedor: 'Comercial Parafusos',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pn-003',
    codigo: 'PN-003',
    nome: 'Pé Nivelador Inox M10 x 50mm',
    descricao: 'Pé nivelador regulável em inox, rosca M10, altura 50mm',
    tipo: 'pes-niveladores',
    altura: 50,
    cargaMaxima: 150,
    rosca: 'M10',
    material: 'Inox 304',
    unidade: 'un',
    custoUnitario: 8.90,
    estoque: 200,
    fornecedor: 'Inox Acessórios',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Parafusos e Fixações
export const parafusos: Parafuso[] = [
  {
    id: 'pf-001',
    codigo: 'PF-001',
    nome: 'Parafuso Sextavado M6 x 20mm',
    descricao: 'Parafuso sextavado cabeça sextavada inox',
    tipo: 'parafusos',
    tipoProduto: 'parafuso',
    dimensao: 'M6x20',
    material: 'Inox 304',
    quantidade_embalagem: 100,
    unidade: 'un',
    custoUnitario: 0.35,
    estoque: 5000,
    fornecedor: 'Comercial Parafusos',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pf-002',
    codigo: 'PF-002',
    nome: 'Parafuso Sextavado M8 x 25mm',
    descricao: 'Parafuso sextavado cabeça sextavada inox',
    tipo: 'parafusos',
    tipoProduto: 'parafuso',
    dimensao: 'M8x25',
    material: 'Inox 304',
    quantidade_embalagem: 100,
    unidade: 'un',
    custoUnitario: 0.55,
    estoque: 4500,
    fornecedor: 'Comercial Parafusos',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pf-003',
    codigo: 'PF-003',
    nome: 'Porca Sextavada M6',
    descricao: 'Porca sextavada inox M6',
    tipo: 'parafusos',
    tipoProduto: 'porca',
    dimensao: 'M6',
    material: 'Inox 304',
    quantidade_embalagem: 100,
    unidade: 'un',
    custoUnitario: 0.15,
    estoque: 6000,
    fornecedor: 'Comercial Parafusos',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pf-004',
    codigo: 'PF-004',
    nome: 'Porca Sextavada M8',
    descricao: 'Porca sextavada inox M8',
    tipo: 'parafusos',
    tipoProduto: 'porca',
    dimensao: 'M8',
    material: 'Inox 304',
    quantidade_embalagem: 100,
    unidade: 'un',
    custoUnitario: 0.25,
    estoque: 5500,
    fornecedor: 'Comercial Parafusos',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pf-005',
    codigo: 'PF-005',
    nome: 'Arruela Lisa M6',
    descricao: 'Arruela lisa inox M6',
    tipo: 'parafusos',
    tipoProduto: 'arruela',
    dimensao: 'M6',
    material: 'Inox 304',
    quantidade_embalagem: 100,
    unidade: 'un',
    custoUnitario: 0.08,
    estoque: 7000,
    fornecedor: 'Comercial Parafusos',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pf-006',
    codigo: 'PF-006',
    nome: 'Rebite Pop 4,0 x 12mm',
    descricao: 'Rebite de repuxo alumínio/aço',
    tipo: 'parafusos',
    tipoProduto: 'rebite',
    dimensao: '4,0x12',
    material: 'Alumínio/Aço',
    quantidade_embalagem: 500,
    unidade: 'un',
    custoUnitario: 0.12,
    estoque: 8000,
    fornecedor: 'Comercial Parafusos',
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Produtos Padronizados - Bancadas e Mesas
export const produtosPadronizados: ProdutoPadrao[] = [
  {
    id: 'bc-001',
    codigo: 'BC-001',
    nome: 'Bancada Lisa Simples 1000x600x850',
    tipo: 'bancada-simples',
    descricao: 'Bancada em inox 304, tampo liso, estrutura em tubo quadrado, 4 pés niveladores',
    dimensoes: {
      largura: 1000,
      profundidade: 600,
      altura: 850,
    },
    componentes: [
      { insumoId: 'mp-003', quantidade: 0.6, observacao: 'Tampo' },
      { insumoId: 'mp-002', quantidade: 0.8, observacao: 'Estrutura lateral' },
      { insumoId: 'pn-001', quantidade: 4, observacao: 'Pés' },
      { insumoId: 'pf-001', quantidade: 16, observacao: 'Fixação estrutura' },
      { insumoId: 'pf-003', quantidade: 16, observacao: 'Porcas' },
      { insumoId: 'pf-005', quantidade: 16, observacao: 'Arruelas' },
    ],
    tempoFabricacao: 180,
    complexidade: 'baixa',
    custoMaterial: 245.80,
    custoMaoObra: 85.00,
    custoTotal: 330.80,
    margemSugerida: 45,
    precoVenda: 479.66,
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'bc-002',
    codigo: 'BC-002',
    nome: 'Bancada com Prateleira 1200x600x850',
    tipo: 'bancada-com-prateleira',
    descricao: 'Bancada em inox 304, tampo liso, prateleira inferior, estrutura reforçada',
    dimensoes: {
      largura: 1200,
      profundidade: 600,
      altura: 850,
    },
    componentes: [
      { insumoId: 'mp-003', quantidade: 0.72, observacao: 'Tampo' },
      { insumoId: 'mp-002', quantidade: 1.2, observacao: 'Estrutura e prateleira' },
      { insumoId: 'pn-002', quantidade: 4, observacao: 'Pés reforçados' },
      { insumoId: 'pf-002', quantidade: 24, observacao: 'Fixação estrutura' },
      { insumoId: 'pf-004', quantidade: 24, observacao: 'Porcas' },
      { insumoId: 'pf-005', quantidade: 24, observacao: 'Arruelas' },
    ],
    tempoFabricacao: 240,
    complexidade: 'media',
    custoMaterial: 358.50,
    custoMaoObra: 120.00,
    custoTotal: 478.50,
    margemSugerida: 50,
    precoVenda: 717.75,
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'bc-003',
    codigo: 'BC-003',
    nome: 'Bancada com 2 Gavetas 1400x700x850',
    tipo: 'bancada-com-gavetas',
    descricao: 'Bancada em inox 304, tampo liso, 2 gavetas laterais, estrutura robusta',
    dimensoes: {
      largura: 1400,
      profundidade: 700,
      altura: 850,
    },
    componentes: [
      { insumoId: 'mp-004', quantidade: 0.98, observacao: 'Tampo reforçado' },
      { insumoId: 'mp-002', quantidade: 2.5, observacao: 'Estrutura, laterais e gavetas' },
      { insumoId: 'pn-002', quantidade: 4, observacao: 'Pés reforçados' },
      { insumoId: 'pf-002', quantidade: 48, observacao: 'Fixação estrutura e gavetas' },
      { insumoId: 'pf-004', quantidade: 48, observacao: 'Porcas' },
      { insumoId: 'pf-006', quantidade: 32, observacao: 'Rebites das gavetas' },
    ],
    tempoFabricacao: 360,
    complexidade: 'alta',
    custoMaterial: 625.90,
    custoMaoObra: 185.00,
    custoTotal: 810.90,
    margemSugerida: 55,
    precoVenda: 1256.90,
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ms-001',
    codigo: 'MS-001',
    nome: 'Mesa Lisa Industrial 1500x800x850',
    tipo: 'mesa-lisa',
    descricao: 'Mesa industrial em inox 304, tampo totalmente liso, estrutura tubular',
    dimensoes: {
      largura: 1500,
      profundidade: 800,
      altura: 850,
    },
    componentes: [
      { insumoId: 'mp-003', quantidade: 1.2, observacao: 'Tampo' },
      { insumoId: 'mp-001', quantidade: 0.8, observacao: 'Reforços estruturais' },
      { insumoId: 'pn-002', quantidade: 4, observacao: 'Pés' },
      { insumoId: 'pf-002', quantidade: 32, observacao: 'Fixação' },
      { insumoId: 'pf-004', quantidade: 32, observacao: 'Porcas' },
    ],
    tempoFabricacao: 210,
    complexidade: 'media',
    custoMaterial: 325.40,
    custoMaoObra: 95.00,
    custoTotal: 420.40,
    margemSugerida: 48,
    precoVenda: 622.19,
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ms-002',
    codigo: 'MS-002',
    nome: 'Mesa com Rebaixo 1800x900x850',
    tipo: 'mesa-com-rebaixo',
    descricao: 'Mesa em inox 304, tampo com rebaixo central para despejo, bordas elevadas',
    dimensoes: {
      largura: 1800,
      profundidade: 900,
      altura: 850,
    },
    componentes: [
      { insumoId: 'mp-004', quantidade: 1.62, observacao: 'Tampo rebaixado' },
      { insumoId: 'mp-002', quantidade: 1.5, observacao: 'Bordas e estrutura' },
      { insumoId: 'pn-002', quantidade: 6, observacao: 'Pés reforçados' },
      { insumoId: 'pf-002', quantidade: 42, observacao: 'Fixação estrutura' },
      { insumoId: 'pf-004', quantidade: 42, observacao: 'Porcas' },
      { insumoId: 'pf-006', quantidade: 56, observacao: 'Rebites bordas' },
    ],
    tempoFabricacao: 420,
    complexidade: 'alta',
    custoMaterial: 548.75,
    custoMaoObra: 215.00,
    custoTotal: 763.75,
    margemSugerida: 52,
    precoVenda: 1160.90,
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ms-003',
    codigo: 'MS-003',
    nome: 'Mesa Industrial Reforçada 2000x1000x900',
    tipo: 'mesa-industrial',
    descricao: 'Mesa industrial heavy-duty, inox 304, estrutura tubular reforçada, prateleira inferior',
    dimensoes: {
      largura: 2000,
      profundidade: 1000,
      altura: 900,
    },
    componentes: [
      { insumoId: 'mp-004', quantidade: 2.0, observacao: 'Tampo reforçado' },
      { insumoId: 'mp-002', quantidade: 2.8, observacao: 'Estrutura e prateleira' },
      { insumoId: 'pn-002', quantidade: 6, observacao: 'Pés heavy-duty' },
      { insumoId: 'pf-002', quantidade: 64, observacao: 'Fixação estrutura' },
      { insumoId: 'pf-004', quantidade: 64, observacao: 'Porcas' },
      { insumoId: 'pf-005', quantidade: 64, observacao: 'Arruelas' },
    ],
    tempoFabricacao: 480,
    complexidade: 'alta',
    custoMaterial: 782.00,
    custoMaoObra: 265.00,
    custoTotal: 1047.00,
    margemSugerida: 58,
    precoVenda: 1654.26,
    ativo: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Consolidar todos os insumos
export const todosInsumos: Insumo[] = [
  ...materiasPrimas,
  ...pesNiveladores,
  ...parafusos,
];
